config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :attender
  resources :event
  root 'event#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessible :email, :password, :password_confirmation
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attender.rb
class Attender < ActiveRecord::Base
	attr_accessible :first_name, :middle_name, :last_name, :name_on_certificate, :email, :phone_number, :event_id, :paid
	belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :name, :venue, :date, :description
	has_many :attenders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attender_controller.rb
class AttenderController < ApplicationController
	def new
	@attender = Attender.new
	@events = Event.all
	end
	def create
	@attender = Attender.new(params[:attender])
	if @attender.save
	redirect_to root_path, notice: "You have been signed up for the event"
	else
	render "new"
	end
	end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
	def index
	@events = Event.all
	end
	def show
	@event = Event.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attender_helper.rb
module AttenderHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/attender/new.html.erb
<%= form_for @attender, url: {action: "create"} do |f| %>
<%= f.label :first_name%>
<%= f.text_field :first_name%> </br>
<%= f.label :middle_name%>
<%= f.text_field :middle_name%> </br>
<%= f.label :last_name%>
<%= f.text_field :last_name%> </br>
<%= f.label :name_on_certificate%>
<%= f.text_field :name_on_certificate%> </br>
<%= f.label :email%>
<%= f.text_field :email%> </br>
<%= f.label :phone_number , "Mobile number"%>
<%= f.text_field :phone_number%> </br>
<%= f.label :event_id , "Event"%>
<%= f.select :event_id, Event.all.collect { |x| [x.name, x.id] } %> </br>
<%= f.submit "Submit" %>
<% end %>

app/views/event/index.html.erb
<% @events.each do |event|%>
	<div>
	<h1><%= event.name%></h1> <small> <%=event.date%>
	<p><%= event.description%> </p>
	<%= link_to "Sign Up", new_attender_path %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TSSAEventplanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>